// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/newsFeed": {
            "get": {
                "description": "Gets a list of all feeds",
                "produces": [
                    "application/json"
                ],
                "summary": "Gets a list of all feeds",
                "parameters": [
                    {
                        "type": "string",
                        "description": "source of the feed",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category of the feed",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "Post a query to get a list of all feeds",
                "produces": [
                    "application/json"
                ],
                "summary": "Post a query to get a list of all feeds",
                "parameters": [
                    {
                        "description": "a map of sources to list of categories",
                        "name": "query",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/feed.feedQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/newsFeed/categories": {
            "get": {
                "description": "Gets a list of all feed categories",
                "produces": [
                    "application/json"
                ],
                "summary": "Gets a list of all feed categories",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/newsFeed/names": {
            "get": {
                "description": "Gets a list of all feed names",
                "produces": [
                    "application/json"
                ],
                "summary": "Gets a list of all feed names",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "feed.feedQuery": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
