definitions:
  feed.feedQuery:
    properties:
      query:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
    type: object
info:
  contact: {}
paths:
  /newsFeed:
    get:
      description: Gets a list of all feeds
      parameters:
      - description: source of the feed
        in: query
        name: source
        type: string
      - description: category of the feed
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: Gets a list of all feeds
    post:
      description: Post a query to get a list of all feeds
      parameters:
      - description: a map of sources to list of categories
        in: body
        name: query
        schema:
          $ref: '#/definitions/feed.feedQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: Post a query to get a list of all feeds
  /newsFeed/categories:
    get:
      description: Gets a list of all feed categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Gets a list of all feed categories
  /newsFeed/names:
    get:
      description: Gets a list of all feed names
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Gets a list of all feed names
swagger: "2.0"
